// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm1tBqsj7rPu9bzrUh_KM6BeyqnuAS70E',
    appId: '1:808966008918:web:38527178b16c055e210bf7',
    messagingSenderId: '808966008918',
    projectId: 'classflow-21b73',
    authDomain: 'classflow-21b73.firebaseapp.com',
    storageBucket: 'classflow-21b73.appspot.com',
    measurementId: 'G-8SDHK6PVXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSj5Rvlh7se-AMP5qxFp0Y-r8YIl0K9pQ',
    appId: '1:808966008918:android:6e336c71f4459c50210bf7',
    messagingSenderId: '808966008918',
    projectId: 'classflow-21b73',
    storageBucket: 'classflow-21b73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3HBElNPA572T4rTV4WClCKKbh0qbh9Og',
    appId: '1:808966008918:ios:e5c13fff3d342708210bf7',
    messagingSenderId: '808966008918',
    projectId: 'classflow-21b73',
    storageBucket: 'classflow-21b73.appspot.com',
    iosClientId: '808966008918-go03eq5j5ou3n0rcc5i89k18u1anijko.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3HBElNPA572T4rTV4WClCKKbh0qbh9Og',
    appId: '1:808966008918:ios:63cf3b67f652b41e210bf7',
    messagingSenderId: '808966008918',
    projectId: 'classflow-21b73',
    storageBucket: 'classflow-21b73.appspot.com',
    iosClientId: '808966008918-1j0b6l0gm5nu3f90qu5r8din2475aoge.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
